config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'pages#login'

  get "photos" => "pages#photos", as: :photos
  get "upload" => "pages#upload", as: :upload

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def photos
  end

  def login
  end

  def upload
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user, :pass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Photofam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/navbar' %>
	<div class="main-page-content <%= controller.controller_name %>">
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/login.html.erb
<% provide(:login, "active") %>  <!--highlight active link, active is bootstrap class -->
<% provide(:title, "Login") %>


<div class="container">
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h3 class="panel-title">Member Login</h3>
  		</div>
  		<div class="panel-body">
  			<form class="form-horizontal">
  				<div class="form-group">
    				<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    				<div class="col-sm-6">
      					<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    				</div>
  				</div>
  				<div class="form-group">
    				<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    				<div class="col-sm-6">
      					<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    				</div>
  				</div>
  				<div class="form-group">
    				<div class="col-sm-offset-2 col-sm-6">
      					<div class="checkbox">
        					<label>
          						<input type="checkbox"> Remember me
        					</label>
      					</div>
    				</div>
  				</div>
  				<div class="form-group">
    				<div class="col-sm-offset-2 col-sm-6">
      					<button type="submit" class="btn btn-default">Sign in</button>
    				</div>
  				</div>
			</form>
  		</div>
	</div>
</div>

app/views/pages/photos.html.erb
<% provide(:photos, "active") %> <!--highlight active link, active is bootstrap class -->
<% provide(:title, "Photos") %>

<div class="container">
	<div class="row">
    	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    	<img class="img-responsive"><%= image_tag "img1.jpg" %>
    	</div>
    	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    	<img class="img-responsive"><%= image_tag "img2.jpg" %>
    	</div>
    	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    	<img class="img-responsive"><%= image_tag "img3.jpg" %>
    	</div>
    	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
	    	<img class="img-responsive"><%= image_tag "img4.jpg" %>
    	</div>
    </div>
</div>

app/views/pages/upload.html.erb
<% provide(:upload, "active") %> <!--highlight active link, active is bootstrap class -->
<% provide(:title, "Upload") %>

<h1>Pages#upload</h1>
<p>Find me in app/views/pages/upload.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container"> <!--removed '-fluid' to line up page content -->
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= yield(:login) %>"><%= link_to "Logout", root_path %></li>
        <li class="<%= yield(:photos) %>"><%= link_to "Photos", photos_path %></li>
        <li class="<%= yield(:upload) %>"><%= link_to "Upload", upload_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :pass %><br>
    <%= f.text_field :pass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user %></td>
        <td><%= user.pass %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @user.pass %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>